### ISSUE TITLE
Not working with UITableview and textfield scrolling up.

### ISSUE THREAD

**Issue by YogeshPateliOS** [kaweerutk/CommonKeyboard#10]
I am using a UITableView. The issue is it scroll more it not perfectly working in UITableViewCell.
It has to show textfield above the keyboard but it shows far than that. Please help me with this. Thank You!

**Comment by kaweerutk** [comment]
@YogeshPateliOS May I know how your view hierarchy construct? or try to debug on this line `let targetFrame = window.convert(responsederView.frame, from: responsederView.superview)` to see if you can get the correct target view position compare to the window view
