### ISSUE TITLE
Issue in subscribe event.

### ISSUE THREAD

**Issue by Razanajam** [kaweerutk/CommonKeyboard#11]
There is an issue in subscribing to keyboard events, when you removeAll and subscribe frequently, subscribe event is not able to subscribe. 

Kindly test this scenario by disabling in viewWillDisappear, and enable on viewWillAppear.

**Comment by kaweerutk** [comment]
Ok I'll check

**Comment by kaweerutk** [comment]
@Razanajam please ensure viewWillAppear get called after viewWillDisappear
