### ISSUE TITLE
Wrong example 2 screen record

### ISSUE THREAD

**Issue by romdevios** [kaweerutk/CommonKeyboard#2]
Something wrong with predictive bar on dismiss end

![Nov-06-2019 15-52-51](https://user-images.githubusercontent.com/12981093/68299822-83468300-00ad-11ea-8c62-e7e0fcc01050.gif)

**Comment by kaweerutk** [comment]
May I know the iOS version.
Is it happens when the screen record enabled?

**Comment by romdevios** [comment]
last versions of iOS 13. iPhone 7

**Comment by kaweerutk** [comment]
This is an iOS default behavior when you tap on empty space the keyboard will resign that's ok but whenever you drag down and keyboard is going to dismiss this will happen only when the word suggestions view appears

**Comment by kaweerutk** [comment]
Or another workaround is when dragging down find the auto-correct view frame and resize there height
