### ISSUE TITLE
Scroll to bottom for tableView when keyboard is shown

### ISSUE THREAD

**Issue by aksthelion** [kaweerutk/CommonKeyboard#8]
I want to add scroll to bottom for table view when keyboard is shown and within view animation. I've following code which works but view flickers multiple times when I drag to dismiss keyboard

    UIView.animate(info, animations: { [weak self] in
        self?.bottomConstraint.constant = bottom
        self?.view.layoutIfNeeded()
        self?.tableView.scrollToBottom()
    })

**Comment by kaweerutk** [comment]
Hey, please look into subscribing evens carefully `.dragDown` will execute frequently depend on dragging. I recommend you to subscribe `.willHide` in order to tableView.scrollToBottom()

```swift
keyboardObserver.subscribe(events: [.willHide]) { [unown self] (info) in
     self.tableView.scrollToBottom()
}
```

**Comment by aksthelion** [comment]
Tx it worked.
