### ISSUE TITLE
Expanding text view with scroll inside it

### ISSUE THREAD

**Issue by aksthelion** [kaweerutk/CommonKeyboard#9]
How do we let text view expand with new lines like we have in Apple's messages app. I've following implementation so far
1) Added height constraints for text view < = 100 in IB
2) Scroll is disabled for text view in IB
3) In textViewDidChange I'm manipulating the height to enable scroll inside text view which does work.

The issue is with text view height which doesn't expand to push table view above, instead it's pushing down text view to hide behind keyboard.

**Comment by kaweerutk** [comment]
Lol bro, this issue is out of the keyboard evens scope. you should implement this by yourself, for example, you need to scroll up when the text view has been changes
